name: freenode
theme: templates
output: out
content-root: content
modules:
  - name: 'null'
    map:
      index: index.html
      archive: artlist.html
  - name: 'blog'
    id: 'news'
    source: news
    root: news
  - name: 'pages'
    id: 'pages'
    source: pages
    root: pages
resources:
  - command: [cat]
    source: static/fonts
    output: out/static/fonts
  - command: [cat]
    source: static/img
    output: out/static/img
    recursive: True
    pattern: '*.png'
  - command: [svgo, -p, '7', -i, -, -o, -]
    source: static/img
    output: out/static/img
    recursive: True
    pattern: '*.svg'
  - command: [myth, --compress, --]
    source: static/css
    output: out/static/css
