name: freenode
COPYRIGHT: "&copy; 2016, freenode"
DESCRIPTION: "freenode IRC network"
GITHUB_URL: "https://github.com/freenode/web-7.0"
SOCIAL:
  - name: Google+
    icon: google-plus
    link: 'https://plus.google.com/104326727082310562426'
  - name: Twitter
    icon: twitter
    link: 'https://twitter.com/freenodestaff'
  - name: Facebook
    icon: facebook
    link: 'https://www.facebook.com/freenode-366911233325305/'
FOOTER:
  !include config/footer.yml
theme: templates
output: out
content-root: content
ignore:
  - '.*'
modules:
  - name: 'null'
    map:
      index: index.html
      archive: artlist.html
      feed: feed.xml
  - name: 'blog'
    id: 'news'
    source: news
    root: news
  - name: 'pages'
    source: pages
    root: ''
  - name: 'faq'
    source: kb
    root: 'kb/answer'
    index_root: 'kb'
    indexes:
      !include config/kb.yml
resources:
  !include config/build.yml
