name: freenode
theme: templates
output: out
content-root: content
modules:
  - name: 'null'
    map:
      index: index.html
      archive: artlist.html
  - name: 'blog'
    id: 'news'
    source: news
    root: news
  - name: 'pages'
    id: 'pages'
    source: pages
    root: pages
resources:
  !include config/build.yml
