- command: [cat]
  source: static/fonts
  output: out/static/fonts
- command: [cat]
  source: static/img
  output: out/static/img
  recursive: True
  pattern: '*.png'
- command: [cat]
  source: static/img
  output: out/static/img
  recursive: True
  pattern: '*.jpg'
- command: [cat]
  source: static/files
  output: out/static/files
- command: [svgo, -p, '7', -i, -, -o, -]
  source: static/img
  output: out/static/img
  recursive: True
  pattern: '*.svg'
- command: [postcss, -c, postcss.json]
  source: static/css
  output: out/static/css
- command: [uglifyjs, -c, -m]
  source: static/js
  output: out/static/js
