- heading: About freenode
  links:
    - name: The project
      link: pages/project
    - name: The people
      link: pages/people
    - name: The philosophy
      link: pages/philosophy
    - name: The policies
      link: pages/policies
    - name: freenode live!
      link: pages/live
    - name: Acknowledgements
      link: pages/acknowledgements
- heading: Using freenode
  links:
    -
      - name: Connect with SSL
        link: 'ircs://chat.freenode.net:6697'
      - name: '/'
      - name: without SSL
        link: 'irc://chat.freenode.net:6667'
    - name: Webchat
      link: '//webchat.freenode.net'
    - name: Channel guidelines
      link: pages/changuide
    - name: Catalyst guidelines
      link: pages/catalysts
    - name: Knowledge base
      link: 'kb/index/all'
    - name: Supporting the project
      link: pages/support
- heading: Groups
  links:
    - name: Group registration
      link: pages/groupreg
    - name: Register as a group
      link: '#'  #XXX  link to gms
    - name: Existing groups
      link: '#'  #XXX  gms integration
